#!/bin/bash
set -euf -o pipefail

MUID=$(id -u)
DEBUG="${DEBUG:-no}"
PORT="${PORT:-2355}"
DIEAFTER="${DIEAFTER:-0s}"
ONESHOT="${ONESHOT:-false}"
PIPEDIR="${PIPEDIR:-/run/pinch}"
DETACH="${DETACH:-true}"

if [[ "$(docker images -q jolynch/pinch-server:latest 2> /dev/null)" == "" ]]; then
    echo "Pulling pinch server docker image"
    docker pull jolynch/pinch-server
fi

if [ ! -d "/run/pinch" ]; then
    echo "Creating /run/pinch"
    sudo mkdir "/run/pinch"
    echo "Chowning /run/pinch to $(whoami)"
    sudo chown -R $MUID /run/pinch
fi

mkdir -p "/run/pinch/in"
mkdir -p "/run/pinch/keys"
mkdir -p "/run/pinch/out"

if [[ "${DETACH}" == "true" ]]; then
    DOCKER_RUN="docker run --rm -d -v /run/pinch/:/run/pinch -p 127.0.0.1:${PORT}:8080 --name pinch-server jolynch/pinch-server pinch-server -listen 0.0.0.0:8080 -die-after ${DIEAFTER}"
else
    DOCKER_RUN="docker run --rm -v /run/pinch/:/run/pinch -p 127.0.0.1:${PORT}:8080 --name pinch-server jolynch/pinch-server pinch-server -listen 0.0.0.0:8080 -die-after ${DIEAFTER}"
fi


if [[ ${DEBUG} != "no" ]]; then
    1>&2 echo "Running ${DOCKER_RUN}"
fi

exec $DOCKER_RUN $@
