#!/bin/bash
set -euf -o pipefail

MUID=$(id -u)
MGUID=$(id -g)
DEBUG="${DEBUG:-no}"
MODE="${MODE:-i}"

if [[ "$(docker images -q jolynch/pinch:latest 2> /dev/null)" == "" ]]; then
    BIN=$(readlink -f "$0")
    DIR=$(dirname $BIN)
    echo "Pulling pinch docker image"
    docker pull jolynch/pinch
fi

# If a terminal, tell docker to run as that as well
if [[ -t 0 ]]; then
    MODE="${MODE}t"
fi

DOCKER_RUN="docker run --rm -${MODE} -u ${MUID}:${MGUID} -v ${PWD}:${PWD}:rw -w ${PWD} --log-driver none --name pinchcmd jolynch/pinch"

if [[ ${DEBUG} != "no" ]]; then
    1>&2 echo "Running ${DOCKER_RUN}"
fi

exec $DOCKER_RUN $@
